### ISSUE TITLE
I have some code about chromium canvas patch.

### ISSUE THREAD

**Issue by nttrung9x** [daijro/camoufox#121]
This code is my collection: https://github.com/nttrung9x/r0chrome_fingerprint_chromium_patch/tree/master/change_code
Hope can apply to camoufox.
Thanks !

**Comment by vlrevolution** [comment]
Can you elaborate? what is missing in camoufox that needs to be added

**Comment by daijro** [comment]
Hello,

Thanks for the code! I saw you're avoid Canvas fingerprinting by randomly offsetting the position and size of `fillRect`. When I was working on Canvas fingerprinting, I originally did the same thing.

However, since Canvas fingerprinting is mostly caused by aliasing, all devices render rectangles the same, as they don't contain diagonal lines. Lots of new WAFs can detect this now by spitting out an image of a rectangle and comparing it to an expected result. Or, more commonly, by drawing an image and redrawing each pixel as small rectangle, then checking if it matches the first image (see #41).

I've made some progress patching Skia's anti-aliasing and other functions to randomize fingerprinting, and I'm hoping to release it soon (although, this patch may be closed source due to this repo being monitored)

**Comment by daijro** [comment]
> @daijro 
> > I've made some progress patching Skia's anti-aliasing and other functions to randomize fingerprinting, and I'm hoping to release it soon (although, this patch may be closed source due to this repo being monitored)
> 
> and will it be used when it is closed? for people? just so I know otherwise thank you for your work I would need a randomization plate and a web gl t, I appreciate your work :)

Yes, the build will still be publicly available, and the release will still be available on GitHub. I will also implement functionality to change the seed in the Python library.

However, the source code for newer high profile patches will be fetched from a locked zip file on my server in the build job.

**Comment by goriyasno** [comment]
@daijro Is there any chances to have your latest build, but without unnecessary to detection rate patches like "disable-extension-newtab.patch" ?

**Comment by nttrung9x** [comment]
Hi @daijro 
Can you share CAMOUFOX_PASSWD ?
