### ISSUE TITLE
cannot pass https://www.browserscan.net/ and https://pixelscan.net/

### ISSUE THREAD

**Issue by satanmp** [daijro/camoufox#14]
![image](https://github.com/user-attachments/assets/dcba93d2-bb98-44fd-a3a2-c4206072720a)
![image](https://github.com/user-attachments/assets/90ca7ac7-98b4-43c9-9419-6b4cee83ab34)

**Comment by daijro** [comment]
Hello,

The detection of proxies isn't done at the browser level, it's done at the network level. Unfortunately there isn't anything that can be done in Camoufox that can fix it, besides switching to a provider that doesn't flag.

The User Agent detection works by checking for JS behavior that is specific to Firefox 130, and comparing it to the claimed userAgent (in this case 125). In my testing, I've only seen this specific to BrowserScan.net, and it doesn't seem to be used by WAFs in production at the moment (maybe in the future). 

Because having a broad range of User Agents is helpful in avoiding detectionbfor most other websites, I've decided against locking the userAgent version in order to get around this edge case. In the future, I do plan on locking it.

**Comment by satanmp** [comment]
> Hello,
> 
> The detection of proxies isn't done at the browser level, it's done at the network level. Unfortunately there isn't anything that can be done in Camoufox that can fix it, besides switching to a provider that doesn't cause flags.
> 
> The User Agent detection works by checking for JS behavior that is specific to Firefox 130, and comparing it to the claimed userAgent (in this case 125). In my testing, I've only seen this specific to BrowserScan.net, and it doesn't seem to be used by WAFs in production at the moment (maybe in the future).
> 
> Because having a broad range of User Agents is helpful in avoiding detection for most other websites, I've decided against locking the userAgent version in order to get around this edge case. In the future, I do plan on locking it.

thanks a lot...，Thank you for your efforts
