### ISSUE TITLE
Can't enable webgl from cfg file

### ISSUE THREAD

**Issue by tserebour** [daijro/camoufox#17]
I turned webgl.disabled(others too) to false in cfg file but still can't see any changes

**Comment by daijro** [comment]
Hi, this needs to be set through the Firefox user prefs:

```python
from camoufox.sync_api import Camoufox

with Camoufox(firefox_user_prefs={"webgl.disabled"': False}) as browser:
    page = browser.new_page()
    page.goto("https://www.example.com")
```

I would not recommend allowing WebGL though, because your true GPU can still be detected based on your allowed WebGL extensions and parameters. The reason it is disabled by default is because of this leak.

I will add a `allow_webgl` parameter to the Python library.
