### ISSUE TITLE
Mobile fingerprints causing detection

### ISSUE THREAD

**Issue by satanmp** [daijro/camoufox#25]
When simulating a mobile browser, entering a search term and simulating clicking on an associated word, the following verification will appear

### It may be related to the istrusted property of click. In puppeteer, it can be bypassed through setJavaScriptEnabled (False), but not in playwright

code:
fg = FingerprintGenerator(browser=('chrome', 'firefox', 'safari', 'edge'), locale=('zh-CN', 'zh',),os=('android', 'ios'),device=('mobile',),)

    with Camoufox(fingerprint=fg.generate(), headless=False, slow_mo=100,block_images=False,proxy={"server": proxy_ip}, config={
        'webrtc:ipv4': public_ip,
    }) as browser:
        page = browser.new_page()
        try:
            page.goto("https://m.toutiao.com/")

            first_keyword = keyword.split('-')[0]
            second_keyword = keyword.split('-')[1]

            keywords = []
            keywords.append(first_keyword)
            for k in second_keyword:
                keywords.append(k)

            input_xpath = "xpath=//input[contains(@placeholder,'搜索或输入')]"
            page.locator(input_xpath).wait_for(timeout=20000)
            page.locator(input_xpath).click()
            input_xpath = "xpath=//input[@name='keyword']"
            page.locator(input_xpath).wait_for(timeout=20000)
            time.sleep(10)

            has_click = False
            for k in keywords:
                if not has_click:
                    page.locator(input_xpath).type(k, delay=100)
                    time.sleep(2)
                    try:
                        page.locator("xpath=//div[@data-extra]").wait_for(timeout=3000)
                        for item in page.locator(
                                "xpath=//div[@data-extra]/a").all():
                            content = item.text_content()
                            if second_keyword in content:
                                item.click()
                                has_click = True
                                break
                    except:
                        pass

            if not has_click:
                page.locator(input_xpath).press("Enter")
![image](https://github.com/user-attachments/assets/25274991-09e6-4657-96a4-c0fc3babcf01)

**Comment by daijro** [comment]
Hello, I've noticed this issue too, and disabled injecting mobile fingerprints in 0.2.6 of the Python library.

Here are some notes:

- iOS's Firefox uses Safari under the hood since Apple doesn't allow third party developers to use any other browser engine other than their WebKit. Because Camoufox uses the Gecko engine, it will be impossible to spoof the WebKit JS engine, so iOS won't be supported in the future.

- Spoofing Android's Firefox should theoretically be possible, and it does score well on CreepJS, but I've noticed that some WAFs are still able to detect it. Likely due to the way input events are handled. I'll do more research into it, but for now Android spoofing won't be supported by Camoufox either.
