### ISSUE TITLE
Fingerprints are not random

### ISSUE THREAD

**Issue by satanmp** [daijro/camoufox#28]
### the canvas、webgl、audio、font fingerprint is the same,Same thing several times
code:
    with Camoufox(headless=False, geoip=True,
                proxy={
                    'server': 'proxy_server',
                    'username': 'username',
                    'password': 'pass'
                },
                humanize = True,
                os=('windows', 'macos', 'linux'),
                slow_mo=100, block_images=True,) as browser:
        page = browser.new_page()
        try:
            page.goto("https://www.browserscan.net/")

![图片](https://github.com/user-attachments/assets/a08b1a0a-a2ef-48f0-9909-adbd3ee0f1bb)

**Comment by daijro** [comment]
Hello, here's a couple notes:

- In Camoufox, WebGL is disabled.  `d616acaa8a5b82727e84b66e71209f5d841f07b0` is BrowserScan's default hash value for when there is no WebGL detected, and `412238758ac572ee55fd2705260e649b6912ad1e` is the default Canvas fingerprint for Firefox 130+ without WebGL. This is expected.
- Audio fingerprint rotation has not been implemented into Camoufox just yet, but Camoufox will hide your device labels. `d970cc255a6553bdb52a03310340dee87c6cf7c1` is BrowserScan's default audio fingerprint when no audio devices labels are detected across all versions of Firefox.
- Font fingerprinting in BrowserScan is based off the names of your installed font families. By default, Camoufox uses the standard set of fonts pulled from Windows 11 22H2, macOS Sonma, and the default Linux fonts used in the TOR browser. It's very unlikely that this set would be used to fingerprinting, since it's as if the user is using a fresh install of the OS without any fonts installed. However, if you'd like to add additional fonts to rotate through, you can randomly passed the names of font families installed on your system into the `fonts` parameter in the Python library.

**Comment by satanmp** [comment]
> Hello, these values are expected. Here's an explanation:
> 
>     * In Camoufox, WebGL is disabled.  `d616acaa8a5b82727e84b66e71209f5d841f07b0` is BrowserScan's default hash value for when there is no WebGL detected, and `412238758ac572ee55fd2705260e649b6912ad1e` is the default Canvas fingerprint for Firefox 130+ without WebGL. This is expected.
> 
>     * Audio fingerprint rotation has not been implemented into Camoufox just yet, but Camoufox will hide your device labels. `d970cc255a6553bdb52a03310340dee87c6cf7c1` is BrowserScan's default audio fingerprint when no audio devices labels are detected. This is the same across all versions of Firefox, and isn't anything specific to Camoufox.
> 
>     * Font fingerprinting in BrowserScan is based off the names of your installed font families. By default, Camoufox uses the standard set of fonts pulled from Windows 11 22H2, macOS Sonma, and the default Linux fonts used in the TOR browser. It's very unlikely that this set would be used to fingerprinting since it's as if the user is using a fresh install of the OS without any fonts installed. However, if you'd like to add additional fonts to rotate through, you can randomly passed the names of font families installed on your system into the `fonts` parameter in the Python library.

thanks

**Comment by tobwen** [comment]
I'm sorry if I'm misunderstanding, but won't that make Camoufox light up in the logs like a burning data centre visible from space?

The fact that WebGL is disabled and no audio device labels are assigned is highly suspicious and immediately indicates that something is wrong.

Shouldn't it be better to ‘blend into the crowd’?

**Comment by daijro** [comment]
> I'm sorry if I'm misunderstanding, but won't that make Camoufox light up in the logs like a burning data centre visible from space?
> 
> The fact that WebGL is disabled and no audio device labels are assigned is highly suspicious and immediately indicates that something is wrong.
> 
> Shouldn't it be better to ‘blend into the crowd’?

Hello, I think my wording was a little confusing. When I said "Camoufox will hide your device labels", I meant that this was a default value in Firefox. Since Firefox 120, Firefox won't report the names of your audio devices.

However, WebGL is disabled in Camoufox by default due to the sheer amount of data it exposes about your system. Since many users don't have WebGL enabled on their devices, many WAFs simply choose to overlook the fact WebGL is disabled. 

In the future, I plan on enabling WebGL by default (support has just been added in the [latest commit](https://github.com/daijro/camoufox/commit/02bc15161a38676e6e85be771e09b91ee5b05c8b)). Although, to implement automatic WebGL fingerprint rotation, I'll need a dataset of existing user data to train a network on (like in Browserforge) which I don't have at the moment.
