### ISSUE TITLE
Detected on youtube.com

### ISSUE THREAD

**Issue by julycreator** [daijro/camoufox#78]
When using a normal browser, you can play YouTube videos without logging in, but when accessing using camoufox, you are required to log in to play videos，, and the homepage is blank.

**Comment by daijro** [comment]
> the homepage is blank.

YouTube shows its "Try searching to get started" when no cookies are found. If you click on a video and go back to the homepage, the videos will show. This same thing happens when opening YouTube in a private tab.

> you can play YouTube videos without logging in,

That's strange, I'm not able to reproduce this. My best guess is that this is something to do with Google flagging you as a fresh browser entering the site for the first time. Could you send a screenshot?

**Comment by OSinoooO** [comment]
Recently, YouTube has strengthened its video download restrictions. When opening YouTube in a new incognito window in Chrome, it prompts to log in, and it might also be an issue with the quality of the IP address. I don't think this is an issue with this project...
